language: python

# command to install dependencies
install:
  - sudo apt-get install graphviz
  - pip install -r requirements.txt

# command to run tests
script: nosetests

# TODO: Setup config file so that we can actually run this
